name: New Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Build Extension and Zip Compression
        run: |
          pnpm zip
          pnpm zip:firefox
          cp .output/*-chrome.zip ./chrome.zip
          cp .output/*-firefox.zip ./firefox.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          body_path: .assets/release.txt
          files: |
            chrome.zip
            firefox.zip
          repository: parintorn0/qr-code-generator
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Addon.Mozilla.Org
        run: pnpm wxt submit --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip
        env:
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
